### PR TITLE
Minor issues

### PR DESCRIPTION
**Pull request by adius**
Hi,

this pull request was created with help of [Feram]!
It's a tool which automatically finds and fixes bugs in your repos.

To view the other patches we created for your code
simply activate [Feram] on [github.com/apps/feram].
Or if you are new to GitHub apps,
check out the full tutorial at [feram.io/help/getting-started].

If you have any feedback or wishes, don't hesitate to contact me
or open an issue at [github.com/feramhq/feram]!

Hope you like it! 😁

[feram.io/help/getting-started]: https://feram.io/help/getting-started
[Feram]: https://www.feram.io
[github.com/apps/feram]: https://github.com/apps/feram
[github.com/feramhq/feram]: https://github.com/feramhq/feram

### CODE REVIEW

**Comment by danpalmer** [comment]
Hi @adius. Thanks for the PR, but I'm afraid it goes against our style guide so we won't be merging this. Unfortunately our style guide isn't public, but if you have a look at some of the linters we use, and specifically the rules we disable, that may give some insight. 

We're happy to change aspects of style where it makes sense, but those changes should be presented with reasons for the change and applied to the whole codebase.

**Comment by adius** [comment]
Hi, sorry that this didn't help.
I thought at least the Python community is in agreement on PEP8.
Are there any config files for your linting we should have picked up automatically?

**Comment by danpalmer** [comment]
I don't think the Python community is agreed on PEP8 in its entirety. There are good bits, but we have a style that is more optimised for smaller git diffs, which PEP8 isn't great at. However there are also many things that we are far stricter on than PEP8 - see our list of flake8 plugins for an idea of what we disallow.

We store all configuration relating to linting tools in `setup.cfg`. Relevant parts are the ignored linting rules, and the files that we ignore. Specifically we currently ignore the test files, as we prioritise pragmatism and higher coverage over the tests looking perfect (however we are considering changing this in the future).

**Comment by adius** [comment]
Thanks for your feedback! I created an issue and we'll look into supporting flake8. Sounds like a cool tool.
https://github.com/feramhq/feram/issues/35

**Pull request closed without merging**
